version: '3'
services:
  app:
    container_name: cakephp_app
    build: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: cakephp_php
    image: php:7.3-rc-fpm
    restart: always
    volumes:
      - ./cakephp/app/webroot:/var/www/html

  db:
    container_name: cakephp_db
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cakephp
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: cakephp