version: '3'
services:
  app:
    container_name: cakephp_app
    build: nginx
    restart: always
    ports:
      - "10080:80"
    depends_on:
      - php
    volumes:
      - ./cakephp:/var/www/html

  php:
    container_name: cakephp_php
    build: php-fpm
    restart: always
    volumes:
      - ./cakephp:/var/www/html

  db:
    container_name: cakephp_db
    image: mysql:5.7
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cakephp
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: cakephp
